version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ledger"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    image: golang:1.25.2
    working_dir: /app/auth
    volumes:
      - ./:/app
    environment:
      HTTP_PORT: "8082"
      GRPC_PORT: "9092"
      JWT_SECRET: "dev-secret"
      AUTH_POSTGRES_DSN: "postgres://postgres:postgres@postgres:5432/ledger?sslmode=disable"
    command: ["go", "run", "./cmd/server"]
    ports:
      - "8082:8082"
      - "9092:9092"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash -c '>/dev/tcp/localhost/8082'"]
      interval: 5s
      timeout: 5s
      retries: 5

  ledger:
    image: golang:1.25.2
    working_dir: /app/ledger
    volumes:
      - ./:/app
    environment:
      HTTP_PORT: "8083"
      GRPC_PORT: "9091"
      POSTGRES_DSN: "postgres://postgres:postgres@postgres:5432/ledger?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
    command: ["go", "run", "./cmd/server"]
    ports:
      - "8083:8083"
      - "9091:9091"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash -c '>/dev/tcp/localhost/8083'"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    image: golang:1.25.2
    working_dir: /app/gateway
    volumes:
      - ./:/app
    environment:
      HTTP_ADDRESS: ":8081"
      AUTH_GRPC_ADDRESS: "auth:9092"
      LEDGER_GRPC_ADDRESS: "ledger:9091"
    command: ["go", "run", "./cmd/gateway"]
    ports:
      - "8081:8081"
    depends_on:
      auth:
        condition: service_healthy
      ledger:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash -c '>/dev/tcp/localhost/8081'"]
      interval: 5s
      timeout: 5s
      retries: 5
